//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netter_HTTP_User.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int LengthLong {
            get {
                return ((int)(this["LengthLong"]));
            }
            set {
                this["LengthLong"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfInt xmlns:xsi=\"http://www.w3.org" +
            "/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <int>" +
            "1</int>\r\n  <int>2</int>\r\n  <int>3</int>\r\n</ArrayOfInt>")]
        public int[] GroupIDs {
            get {
                return ((int[])(this["GroupIDs"]));
            }
            set {
                this["GroupIDs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Безопасность</string>
  <string>Климат</string>
  <string>Освещение</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection GroupTitles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["GroupTitles"]));
            }
            set {
                this["GroupTitles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Дверь</string>\r\n  <string>Окно</string>\r\n  <string>Пол</string>\r\n</ArrayOf" +
            "String>")]
        public global::System.Collections.Specialized.StringCollection TypeTitles_of_SecurityGroup {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TypeTitles_of_SecurityGroup"]));
            }
            set {
                this["TypeTitles_of_SecurityGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection TypeTitles_of_ClimateGroup {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TypeTitles_of_ClimateGroup"]));
            }
            set {
                this["TypeTitles_of_ClimateGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Лампа</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TypeTitles_of_LightingGroup {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TypeTitles_of_LightingGroup"]));
            }
            set {
                this["TypeTitles_of_LightingGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfInt xmlns:xsi=\"http://www.w3.org" +
            "/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <int>" +
            "1</int>\r\n  <int>2</int>\r\n  <int>3</int>\r\n</ArrayOfInt>")]
        public int[] TypeIDs_of_SecurityGroup {
            get {
                return ((int[])(this["TypeIDs_of_SecurityGroup"]));
            }
            set {
                this["TypeIDs_of_SecurityGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int[] TypeIDs_of_ClimateGroup {
            get {
                return ((int[])(this["TypeIDs_of_ClimateGroup"]));
            }
            set {
                this["TypeIDs_of_ClimateGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfInt xmlns:xsi=\"http://www.w3.org" +
            "/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <int>" +
            "1</int>\r\n</ArrayOfInt>")]
        public int[] TypeIDs_of_LightingGroup {
            get {
                return ((int[])(this["TypeIDs_of_LightingGroup"]));
            }
            set {
                this["TypeIDs_of_LightingGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Открыто</string>
  <string>Закрыто</string>
  <string>Заблокировано</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Door_Position {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Door_Position"]));
            }
            set {
                this["Door_Position"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8888/")]
        public string DefaultURI {
            get {
                return ((string)(this["DefaultURI"]));
            }
            set {
                this["DefaultURI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Netter")]
        public string ProjectName {
            get {
                return ((string)(this["ProjectName"]));
            }
            set {
                this["ProjectName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int LengthShot {
            get {
                return ((int)(this["LengthShot"]));
            }
            set {
                this["LengthShot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("oprt")]
        public string PostRequest_Operation {
            get {
                return ((string)(this["PostRequest_Operation"]));
            }
            set {
                this["PostRequest_Operation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>on</string>
  <string>off</string>
  <string>get</string>
  <string>set</string>
  <string>lp</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PostRequest_OperationValue {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PostRequest_OperationValue"]));
            }
            set {
                this["PostRequest_OperationValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfInt xmlns:xsi=\"http://www.w3.org" +
            "/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <int>" +
            "3</int>\r\n  <int>3</int>\r\n</ArrayOfInt>")]
        public int[] OptionNumber_of_SecurityGroup {
            get {
                return ((int[])(this["OptionNumber_of_SecurityGroup"]));
            }
            set {
                this["OptionNumber_of_SecurityGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int[] OptionNumber_of_ClimateGroup {
            get {
                return ((int[])(this["OptionNumber_of_ClimateGroup"]));
            }
            set {
                this["OptionNumber_of_ClimateGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfInt xmlns:xsi=\"http://www.w3.org" +
            "/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <int>" +
            "3</int>\r\n</ArrayOfInt>")]
        public int[] OptionNumber_of_LightingGroup {
            get {
                return ((int[])(this["OptionNumber_of_LightingGroup"]));
            }
            set {
                this["OptionNumber_of_LightingGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Открыть</string>
  <string>Проветривание</string>
  <string>Закрыть</string>
  <string>Заблокировать</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Window_Position {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Window_Position"]));
            }
            set {
                this["Window_Position"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:03")]
        public global::System.TimeSpan DefaultRepeatedRequestTimer {
            get {
                return ((global::System.TimeSpan)(this["DefaultRepeatedRequestTimer"]));
            }
            set {
                this["DefaultRepeatedRequestTimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:03")]
        public global::System.TimeSpan DefaultResponseTimeOut {
            get {
                return ((global::System.TimeSpan)(this["DefaultResponseTimeOut"]));
            }
            set {
                this["DefaultResponseTimeOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int MaxCountMessageLine {
            get {
                return ((int)(this["MaxCountMessageLine"]));
            }
            set {
                this["MaxCountMessageLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:01:00")]
        public global::System.TimeSpan MaxRepeatedRequestTimer {
            get {
                return ((global::System.TimeSpan)(this["MaxRepeatedRequestTimer"]));
            }
            set {
                this["MaxRepeatedRequestTimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int MaxRepeatRequest {
            get {
                return ((int)(this["MaxRepeatRequest"]));
            }
            set {
                this["MaxRepeatRequest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("admin/")]
        public string RawURI_Admin {
            get {
                return ((string)(this["RawURI_Admin"]));
            }
            set {
                this["RawURI_Admin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:30")]
        public global::System.TimeSpan DefaultSaveResponseTimeOut {
            get {
                return ((global::System.TimeSpan)(this["DefaultSaveResponseTimeOut"]));
            }
            set {
                this["DefaultSaveResponseTimeOut"] = value;
            }
        }
    }
}
