//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netter_HTTP_Server.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int LengthLong {
            get {
                return ((int)(this["LengthLong"]));
            }
            set {
                this["LengthLong"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfInt xmlns:xsi=\"http://www.w3.org" +
            "/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <int>" +
            "1</int>\r\n  <int>2</int>\r\n  <int>3</int>\r\n</ArrayOfInt>")]
        public int[] GroupIDs {
            get {
                return ((int[])(this["GroupIDs"]));
            }
            set {
                this["GroupIDs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Безопасность</string>
  <string>Климат</string>
  <string>Освещение</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection GroupTitles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["GroupTitles"]));
            }
            set {
                this["GroupTitles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Дверь</string>\r\n  <string>Окно</string>\r\n  <string>Пол</string>\r\n</ArrayOf" +
            "String>")]
        public global::System.Collections.Specialized.StringCollection TypeTitles_of_SecurityGroup {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TypeTitles_of_SecurityGroup"]));
            }
            set {
                this["TypeTitles_of_SecurityGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection TypeTitles_of_ClimateGroup {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TypeTitles_of_ClimateGroup"]));
            }
            set {
                this["TypeTitles_of_ClimateGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Лампа</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TypeTitles_of_LightingGroup {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TypeTitles_of_LightingGroup"]));
            }
            set {
                this["TypeTitles_of_LightingGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:05")]
        public global::System.TimeSpan DefaultSearchTimer {
            get {
                return ((global::System.TimeSpan)(this["DefaultSearchTimer"]));
            }
            set {
                this["DefaultSearchTimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfInt xmlns:xsi=\"http://www.w3.org" +
            "/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <int>" +
            "1</int>\r\n  <int>2</int>\r\n  <int>3</int>\r\n</ArrayOfInt>")]
        public int[] TypeIDs_of_SecurityGroup {
            get {
                return ((int[])(this["TypeIDs_of_SecurityGroup"]));
            }
            set {
                this["TypeIDs_of_SecurityGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int[] TypeIDs_of_ClimateGroup {
            get {
                return ((int[])(this["TypeIDs_of_ClimateGroup"]));
            }
            set {
                this["TypeIDs_of_ClimateGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfInt xmlns:xsi=\"http://www.w3.org" +
            "/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <int>" +
            "1</int>\r\n</ArrayOfInt>")]
        public int[] TypeIDs_of_LightingGroup {
            get {
                return ((int[])(this["TypeIDs_of_LightingGroup"]));
            }
            set {
                this["TypeIDs_of_LightingGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Открыто</string>
  <string>Закрыто</string>
  <string>Заблокировано</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Door_Position {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Door_Position"]));
            }
            set {
                this["Door_Position"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8888/")]
        public string DefaultURI {
            get {
                return ((string)(this["DefaultURI"]));
            }
            set {
                this["DefaultURI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Netter")]
        public string ProjectName {
            get {
                return ((string)(this["ProjectName"]));
            }
            set {
                this["ProjectName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>ON</string>\r\n  <string>OFF</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ServerStatus {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ServerStatus"]));
            }
            set {
                this["ServerStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int LengthShot {
            get {
                return ((int)(this["LengthShot"]));
            }
            set {
                this["LengthShot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("oprt")]
        public string PostRequest_Operation {
            get {
                return ((string)(this["PostRequest_Operation"]));
            }
            set {
                this["PostRequest_Operation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>on</string>
  <string>off</string>
  <string>get</string>
  <string>set</string>
  <string>lp</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PostRequest_OperationValue {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PostRequest_OperationValue"]));
            }
            set {
                this["PostRequest_OperationValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfInt xmlns:xsi=\"http://www.w3.org" +
            "/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <int>" +
            "8</int>\r\n  <int>8</int>\r\n</ArrayOfInt>")]
        public int[] OptionNumber_of_SecurityGroup {
            get {
                return ((int[])(this["OptionNumber_of_SecurityGroup"]));
            }
            set {
                this["OptionNumber_of_SecurityGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int[] OptionNumber_of_ClimateGroup {
            get {
                return ((int[])(this["OptionNumber_of_ClimateGroup"]));
            }
            set {
                this["OptionNumber_of_ClimateGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfInt xmlns:xsi=\"http://www.w3.org" +
            "/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <int>" +
            "8</int>\r\n</ArrayOfInt>")]
        public int[] OptionNumber_of_LightingGroup {
            get {
                return ((int[])(this["OptionNumber_of_LightingGroup"]));
            }
            set {
                this["OptionNumber_of_LightingGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("statustimer")]
        public string DeleteTimerTitle {
            get {
                return ((string)(this["DeleteTimerTitle"]));
            }
            set {
                this["DeleteTimerTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:15")]
        public global::System.TimeSpan DefaultDeleteTimer {
            get {
                return ((global::System.TimeSpan)(this["DefaultDeleteTimer"]));
            }
            set {
                this["DefaultDeleteTimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int TimeOutMultiplication {
            get {
                return ((int)(this["TimeOutMultiplication"]));
            }
            set {
                this["TimeOutMultiplication"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int MaxCountMessageLine {
            get {
                return ((int)(this["MaxCountMessageLine"]));
            }
            set {
                this["MaxCountMessageLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>uri</string>
  <string>statustimer</string>
  <string>responsetimer</string>
  <string>pausetimer</string>
  <string>repeat</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AdminDeviceOptions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AdminDeviceOptions"]));
            }
            set {
                this["AdminDeviceOptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int MaxNumberOfWaitingUsers {
            get {
                return ((int)(this["MaxNumberOfWaitingUsers"]));
            }
            set {
                this["MaxNumberOfWaitingUsers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("admin")]
        public string AdminLogin {
            get {
                return ((string)(this["AdminLogin"]));
            }
            set {
                this["AdminLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("admin")]
        public string AdminPassword {
            get {
                return ((string)(this["AdminPassword"]));
            }
            set {
                this["AdminPassword"] = value;
            }
        }
    }
}
